#? https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu

- name: system setup | drivers | copy displaylink driver archive # https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu
  tags: distro-setup, dirvers, displaylink
  ansible.builtin.get_url:
    url: https://www.synaptics.com/sites/default/files/Ubuntu/pool/stable/main/all/synaptics-repository-keyring.deb
    dest: /home/fabrice/downloads/synaptics-repository-keyring.deb
    owner: fabrice
    group: fabrice
    mode: 0600
    when: ansible_distribution in ["Debian", "Ubuntu"]

- name: system setup | drivers | install .deb package
  tags: distro-setup, dirvers, displaylink
  apt:
    deb: /home/fabrice/downloads/synaptics-repository-keyring.deb

- name: system setup | drivers | update package cache (debian, etc)
  tags: distro-setup, dirvers, displaylink
  apt: update_cache=yes
  changed_when: False
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: system setup | drivers | install displaylink driver
  tags: distro-setup, dirvers, displaylink
  apt:
    name: displaylink-driver
    state: present