- name: gnome | appearance | copy wallpaper file
  tags: gnome,gnome-wallpaper
  copy:
    src: gnome/wallpaper.png
    dest: /usr/share/backgrounds/fabrice-wallpaper.png
    owner: root
    group: root
    mode: 0644

- name: gnome | appearance | set wallpaper
  tags: gnome,gnome-wallpaper
  become_user: fabrice
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/fabrice-wallpaper.png'"

- name: gnome | appearance | set wallpaper position
  tags: gnome,gnome-wallpaper
  become_user: fabrice
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: gnome | appearance | copy lock screen background file
  tags: gnome,gnome-lockscreen
  copy:
    src: files/gnome/lockscreen.jpg
    dest: /usr/share/backgrounds/fabrice-lockscreen.jpg
    owner: root
    group: root
    mode: 0644

- name: gnome | appearance | set lock screen background
  tags: gnome,gnome-lockscreen
  become_user: fabrice
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file:///usr/share/backgrounds/fabrice-lockscreen.jpg'"

- name: gnome | appearance | set lock screen background position
  tags: gnome,gnome-lockscreen
  become_user: fabrice
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-options"
    value: "'zoom'"

# - name: gnome | appearance | gnome | appearance | set icon theme
#   become_user: fabrice
#   dconf:
#     key: "/org/gnome/desktop/interface/icon-theme"
#     value: "'Moka-Minimal'"

# - name: gnome | appearance | install GTK theme
#   apt: name=arc-theme

# - name: gnome | appearance | set GTK theme
#   become_user: fabrice
#   dconf:
#     key: "/org/gnome/desktop/interface/gtk-theme"
#     value: "'Arc-Dark'"

# - name: gnome | appearance | set shell theme
#   become_user: fabrice
#   dconf:
#     key: "/org/gnome/shell/extensions/user-theme/name"
#     value: "'Arc-Dark'"

- name: gnome | appearance | checkout stylepack
  tags: gnome,gnome-theme
  git:
    repo: 'https://github.com/refi64/stylepak.git'
    dest: /tmp/stylepak

- name: gnome | appearance | install stylepack pre-requisites - 1
  apt: name=ostree

- name: gnome | appearance | install stylepack pre-requisites - 2
  apt: name=appstream-util

- name: gnome | appearance | allow flatpack override
  become_user: fabrice
  tags: gnome,gnome-theme
  shell: flatpak override --filesystem=xdg-config/gtk-4.0

- name: gnome | appearance | install Orchis GTK theme
  tags: gnome,gnome-theme
  shell: /tmp/stylepak/stylepak install-user Orchis
