- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: b

- name: "Ansible | Creating a file with content"
  copy:
    dest: /tmp/install-homebrew.sh
    content: |
      #!/bin/bash
      yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not b.stat.exists

- name: Install Homebrew
  shell: sudo -E sh /tmp/install-homebrew.sh  # The -E flag preserves the environment variables
  when: not b.stat.exists
  become: no

# - name: Remove install script
#   file:
#     path: /tmp/install-homebrew.sh
#     state: absent
#   become: yes
