- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - "{{ cron_package }}"
    state: latest

- name: system setup | cron | start and enable cronie daemon
  tags: cron
  service:
    name: cronie
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"

- name: system setup | cron | schedule automatic ansible provisioning #TODO: review this task (original user was "simone")
  tags: cron
  cron:
    name: "ansible provision"
    user: fabrice
    hour: "{{ ansible_cron_hour | default('*') }}"
    minute: "{{ ansible_cron_minute | default('*/30') }}"
    job: "/usr/local/bin/provision > /dev/null"

- name: system setup | cron | schedule ansible cleanup at boot #TODO: review this task (original user was "simone")
  tags: cron
  cron:
    name: "ansible refresh at boot"
    user: fabrice
    special_time: reboot
    job: "/bin/rm -rf /home/fabrice/.ansible"
